image: docker.slock.it/build-images/node:11-alpine
variables:
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-in3:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
  artifacts:
    paths:
      - js/


test-in3-parity:
  stage: test
  tags:
    - short-jobs
  variables:
    RPCURL: http://parity:8545
    IPFS_URL: http://ipfs:5001
  services:
    - name: jbenet/go-ipfs:latest
      command:
        - daemon
        - --offline
      alias: ipfs
    - name: docker.slock.it/core-technology/parity-timemachine:master
      alias: parity
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
    - npm test
    - rm -rf in3-server; git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/in3/ts/in3-server.git -b develop --single-branch
    - cd in3-server
    - npm install
    - cd node_modules
    - rm -rf in3
    - ln -s ../../ in3
    - cd ..
    - npm run build
    - npm test
  
test-in3-geth:
  stage: test
  tags:
    - short-jobs
  variables:
    RPCURL: http://geth:8545
    IPFS_URL: http://ipfs:5001
  services:
    - name: jbenet/go-ipfs:latest
      command:
        - daemon
        - --offline
      alias: ipfs
    - name: docker.slock.it/core-technology/geth-timemachine:master
      alias: geth
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
    - npm test
    - rm -rf in3-server; git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/in3/ts/in3-server.git -b develop --single-branch
    - cd in3-server
    - npm install
    - cd node_modules
    - rm -rf in3
    - ln -s ../../ in3
    - cd ..
    - npm run build
    - npm test

  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report

test-implementation:
  stage: test
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
    - npm test
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/in3/ts/in3-implementation-tests.git
    - cd in3-implementation-tests
    - npm install
    - cd node_modules
    - ln -s ../../ in3
    - cd ..
    - npm run build-ts
#    - npm test; echo "done"

test-in3-examples:
  stage: test
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - cd examples/
    - npm install
    - npm run start

test-usn-lib:
  stage: test
  tags:
    - short-jobs
  variables:
    RPCURL: http://parity:8545
    USN_TESTMODE: parity
    TEST_RESULTS: test/results/parity/
    TEST_SCOPE: short
  services:
    - name: parity/parity:stable
      command:
        - --jsonrpc-experimental
        - --jsonrpc-apis=all
        - --logging=3
        - --jsonrpc-interface=all
        - --ws-interface=all
        - --chain=dev
        - --gas-cap=8000000
        - --gasprice=0
        - --reseal-min-period=0
        - --gas-floor-target=8700000
        - --tracing=on
      alias: parity
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
    - cd ..
    - rm -rf usn-testing
    - mkdir usn-testing
    - cd usn-testing
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/iotlayer/usn-lib.git -b 168-fixing-util-types-and-serialize-references --single-branch
    - cd usn-lib
    - npm install
    - rm -rf node_modules/in3
    - cd node_modules
    - ln -s /builds/in3/ts/in3 in3
    - cd ..
    - npm run build
    - npm test; echo "done"
    - cd ..
    - rm -rf usn-testing

pages:
  stage: deploy
  tags:
    - short-jobs
  environment:
    name: test-results
    url: http://in3.git-pages.slock.it/in3
  dependencies:
    - test-in3-parity
    - test-in3-geth
  script:
    - mkdir -p public/
    - cp -r test/report/* public/
  artifacts:
    paths:
      - public

deploy-to-slockit-npm:
  stage: deploy
  tags:
    - short-jobs
  only: # deploy only on  semantic versions tags
    - /^v[0-9]*\.[0-9]*\.[0-9]*-?.*$/
  except:
    - branches
  dependencies:
    - build-in3
  script:
    - sh /prepare.sh
    - npm --no-git-tag-version --allow-same-version -f version $CI_COMMIT_TAG
    - npm publish

deploy-to-slockit-public_npm:
  stage: deploy
  tags:
    - short-jobs
  only:
    - /^v[0-9]+.[0-9]+.[0-9]+$/
  except:
    - branches
  dependencies:
    - build-in3
  script:
    - sh /prepare.sh
    - npm --no-git-tag-version --allow-same-version -f version $CI_COMMIT_TAG
    - npm publish --registry https://registry.npmjs.org

deploy-docker:
  stage: deploy
  tags:
    - short-jobs
  services:
    - docker:dind
  image: jonaskello/docker-and-compose:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $COMMIT_IMAGE_TAG .
    - docker tag $COMMIT_IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG
    - docker push $COMMIT_IMAGE_TAG
